CREATE TABLE IF NOT EXISTS books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    author VARCHAR(255),
    isbn VARCHAR(255),
    title VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS borrowers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS book_borrows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    borrowed_at TIMESTAMP(6) NOT NULL,
    returned_at TIMESTAMP(6),
    book_id BIGINT NOT NULL REFERENCES books (id),
    borrower_id BIGINT NOT NULL REFERENCES borrowers (id)
);

CREATE INDEX IF NOT EXISTS idx_active_book_borrow
ON book_borrows (book_id, returned_at);

CREATE UNIQUE INDEX IF NOT EXISTS uk_active_book_borrow
ON book_borrows (book_id)
WHERE returned_at IS NULL;
